# Generated by Django 4.2.14 on 2024-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_city_rename_customer_order_order_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order',
            field=models.DateField(null=True),
        ),
    ]
