# Generated by Django 4.2.14 on 2024-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer_last_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_order',
            field=models.DateField(blank=True, null=True),
        ),
    ]
