# Generated by Django 4.2.14 on 2024-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
