# Generated by Django 4.2.14 on 2024-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customer_city_delete_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=25),
        ),
    ]
