# Generated by Django 4.2.14 on 2024-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
