# Generated by Django 4.2.14 on 2024-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customer_total_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
