# Generated by Django 4.2.14 on 2024-08-24 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.IntegerField(default=0)),
                ('used_weight', models.IntegerField(default=0)),
                ('packed_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.IntegerField(default=0)),
                ('produced_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='finished_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='required_packaging',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='required_production',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unpacked_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RequiredItem',
        ),
        migrations.AddField(
            model_name='productionplanitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='productionplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productionplan'),
        ),
        migrations.AddField(
            model_name='packagingplanitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='packagingplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.packagingplan'),
        ),
    ]
